#pragma once

#define KEXPLORE_IOCTL_GET_EXPORTED_NAME        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x900, METHOD_BUFFERED, FILE_READ_ACCESS)
#define KEXPLORE_IOCTL_READ_MEMORY              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x901, METHOD_IN_DIRECT, FILE_READ_ACCESS)
#define KEXPLORE_IOCTL_WRITE_MEMORY             CTL_CODE(FILE_DEVICE_UNKNOWN, 0x902, METHOD_OUT_DIRECT, FILE_WRITE_ACCESS)
#define KEXPLORE_IOCTL_ENUM_JOBS                CTL_CODE(FILE_DEVICE_UNKNOWN, 0x903, METHOD_BUFFERED, FILE_READ_ACCESS)
#define KEXPLORE_IOCTL_ENUM_CHILD_JOBS          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x904, METHOD_BUFFERED, FILE_READ_ACCESS)
#define KEXPLORE_IOCTL_OPEN_OBJECT_HANDLE       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x905, METHOD_BUFFERED, FILE_READ_ACCESS)

struct OpenHandleData {
    PVOID Object;
    ACCESS_MASK AccessMask;
};
